# Generated by Django 2.0.5 on 2018-05-28 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lasttname', models.CharField(blank=True, max_length=50)),
                ('address1', models.TextField(blank=True, max_length=500)),
                ('address2', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.IntegerField(choices=[(1, 'Delivery Address'), (2, 'Billing  Address')], default=1)),
                ('card_holder_name', models.CharField(blank=True, max_length=100)),
                ('cc_number', models.CharField(blank=True, max_length=16)),
                ('expiray_month', models.CharField(blank=True, max_length=3)),
                ('expiray_year', models.CharField(blank=True, max_length=4)),
                ('cvv_number', models.CharField(blank=True, max_length=4)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile'),
        ),
    ]
