# Generated by Django 2.0.6 on 2018-06-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='API.Checkout'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='API.Proxies'),
        ),
        migrations.AlterField(
            model_name='task',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='API.ShopifyUrl'),
        ),
    ]
