# Generated by Django 2.0.5 on 2018-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'Delivery Address'), (2, 'Billing  Address')], default=1),
        ),
    ]
