# Generated by Django 2.0.5 on 2018-05-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180528_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cc_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cvv_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiray_month',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expiray_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
