# Generated by Django 2.0.5 on 2018-06-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20180531_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('size', models.TextField(blank=True, max_length=500)),
                ('billing_profile', models.TextField(blank=True, max_length=500)),
                ('proxy', models.TextField(blank=True, max_length=500)),
                ('checkout_type', models.CharField(blank=True, max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paypal_use',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
