# Generated by Django 2.0.5 on 2018-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_gmail_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('port', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
