# Generated by Django 2.0.5 on 2018-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_proxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopifyurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
