# Generated by Django 2.0.5 on 2018-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_shopifyurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyurl',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
