# Generated by Django 2.0.5 on 2018-06-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20180608_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gmail_account',
            new_name='GmailAccount',
        ),
    ]
