# Generated by Django 2.0.5 on 2018-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20180611_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='keyword',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
