# Generated by Django 2.0.5 on 2018-06-11 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_task_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='API.Checkout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('ReSearching', 'ReSearching'), ('NotResult', 'NotResult'), ('Not Available', 'Not Available'), ('Checkouting', 'Checkouting'), ('Pin Required', 'Pin Required'), ('Pin Checking', 'Pin Checking'), ('Pin Invalid', 'Pin Invalid'), ('Captcha solving', 'Captcha solving'), ('Error', 'Error'), ('Done', 'Done')], default='Queued', max_length=20),
        ),
    ]
