# Generated by Django 2.0.5 on 2018-06-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20180611_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='API.Checkout'),
        ),
    ]
